# -*- coding: utf-8 -*-
"""LABCYCLE QUESTION : 05new.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11xjsGl_4GESrK0ihCzT43-wIEMofIR-Y

# ***PYTHON LABCYCLE QUESTION : 05***
"""

#5.Develop a program to read a string and perform the following operations:

#• Print all possible substring

#• Print all possible substrings of length K

#• Print all possible substrings of length K with N distinct characters

#• Print all palindrome substrings

def subString(a):
  for i in range(0,len(a)+1):
    for j in range(i+1,len(a)+1):
      s = a[i:j]
      print(s,end="  ")
def substringk(a,size):
  for i in range(0,len(a)+1):
    for j in range(i+1,len(a)+1):
      s = a[i:j]
      if len(s)==size:
        print(s,end="  ")
def substringN(a,size,N):
  for i in range(0,len(a)+1):
    for j in range(i+1,len(a)+1):
      s = a[i:j]
      if len(s)==size:
        distinct = set(s)
        if len(distinct) == N:
          print(s,end="  ")

def paliandrome(a):
  for i in range(0,len(a)+1):
    for j in range(i+1,len(a)+1):
      s = a[i:j]
      reverse = s[::-1]
      if reverse == s:
        print(s , end = "  ")


a = input("Enter the string :  ")
print("1.Sub Strings are")
subString(a)

length = int(input("\n\nEnter length of the substring "))
print("\n2.Sub Strings with length ",length," are")
substringk(a,length) 

num_of_distinct = int(input("\n\nEnter the no of distinct characters : "))
print("\n3.Sub Strings with length ",length,"and ",num_of_distinct," distinct characters are")
substringN(a,length,num_of_distinct)

print("\n\n4.The Paliandrome subStrings are ")
paliandrome(a)