# -*- coding: utf-8 -*-
"""LAB2Q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VfR6OFUMlv1x4TCJyneobkwUnStbUE-T

# ***PYTHON LABCYCLE 2 QUESTION 2***

5.Write a program to create a parent class, 3DShapes, with methods 
printVolume() and printArea(), which prints the Volume and Area,
respectively. Create classes Cylinder and Sphere by inheriting
3DShapes class. Using these child classes, calculate and print the
volume and area of a cylinder and sphere.
"""

class  threeDShapes:
  def printVolume(shape):
    print(" Volume is: ",shape.Volume)
  def printArea(shape):
    print(" Area is :",shape.Area)
  

class Cylinder( threeDShapes):
  
  def __init__(shape,r,h):
    shape.Radius = r
    shape.Height = h
  def calcArea(shape):
    shape.Area = 2*3.14*shape.Radius*(shape.Radius+shape.Height)
  def calcVolume(shape):
    shape.Volume = round((3.14*shape.Radius*shape.Radius*shape.Height),2)


class Sphere( threeDShapes):
    
    def __init__(shape,r):
      shape.Radius = r
    def calcArea(shape):
      shape.Area = 4*3.14*shape.Radius*shape.Radius
    def calcVolume(shape):
      shape.Volume = round(((4/3)*3.14*(shape.Radius**3)),2)



RadiusCylinder = int(input("Enter the radius of the cylinder "))
HeightCylinder = int(input("Enter the height of the cylinder "))
calcCylinder = Cylinder(RadiusCylinder,HeightCylinder)
calcCylinder.calcArea()
calcCylinder.printArea()
calcCylinder.calcVolume()
calcCylinder.printVolume()


RadiusSphere = int(input("\nEnter the radius of the sphere : "))
calcSphere = Sphere(RadiusSphere)
calcSphere.calcArea()
calcSphere.calcVolume()
calcSphere.printArea()
calcSphere.printVolume()