# -*- coding: utf-8 -*-
"""LAB2Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mF94RyOvX8igtzlOjyzzvWe4asBSu22Z

# **         PYTHON LAB CYCLE 2     **

Q1 : Suppose a newly born pair of rabbits, one male and one female, are 
put in a field. Rabbits can mate at the age of one month so that at the 
end of its second month, a female has produced another pair of 
rabbits. Suppose that our rabbits never die and that the female always 
produces one new pair every month from the second month.
Develop a program to show a table containing the number of pairs of 
rabbits in the first N months.
"""

n=int(input("Enter number of months : "))
def fibonacci(n):

  if n==1:
    return 1
  elif n==2:
    return 1
  elif n>2:
    return fibonacci(n-1)+fibonacci(n-2)
fibonacci(n)    

print("Number of rabits upto " ,n,"months : ")
print('Month           Number of pair of rabits')  
for i in range(1,n+1):
  print(i,"\t\t",fibonacci(i))