# -*- coding: utf-8 -*-
"""PythonAssignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g2U9U9eBAR9LGfnVGfxhQytR8sNDDqms

*1.WRITE A PROGRAM TO PRINT AVERGARE OF THREE NUMBERS.*
"""

a = int(input('Enter first number:'))
b = int(input('Enter second number:'))
c = int(input('Enter third number:'))
average = ((a+b+c)/3)
print("Average=",average)

"""*2.WRITE A PROGRAM TO PRINT SUM AND AVERAGE OF THREE NUMBERS*"""

a = int(input('Enter first number:'))
b = int(input('Enter second number:'))
c = int(input('Enter third number:'))
sum = a+b+c
average = ((a+b+c)/3))

print("SUM=",sum)
print("AVERAGE=",average)

"""3.WRITE A PROGRAM TO PRINT AREA AND PERIMETER OF A TRIANGLE."""

a = int(input('Length of side one :'))
b = int(input('Length of side two :'))
c = int(input('Length of side three :'))
perimeter = a+b+c
p = (a+b+c)/2
area = math.sqrt((p*(p-a)*(p-b)*(p-c)))
print("PERIMETER OF TRIANGLE:",perimeter)
print("AREA OF TRIANGLE:",area)

"""*4.WRITE A PROGRAM TO CONVERT THE TIME ENTERED IN SECONDS TO HOURS , MINUTES , AND SECONDS*"""

numberOfSeconds = float(input('Enter the number of seconds:'))
seconds = numberOfSeconds
minutes = seconds/60
hours = minutes/60
print("Given value in hours is :",hours)
print("Given value in minutes is :",minutes)
print("Given value in seconds is :",seconds)

"""*5.WRITE A PROGRAM TO PRINT AREA OF A CIRCLE.*"""

r = int(input('Enter radius of circle:'))
area = math.pi*r*r
print("Area of circle is ",area)

"""*6.WRITE A PROGRAM TO ENTER TWO UNEQUAL NUMBER AND INTERCHANGE THEM WITHOUT USING THIRD VARIABLE.*"""

a = int(input('Enter first number :'))
 b = int(input('Enter second number : '))
 print("a =",a)
 print("b =",b)
 a = a+b
 b = a-b
 a = a-b
 print("After swapping : ",a,b)

"""*7.WRITE A PROGRAM TO ENTER THE NUMBER OF DAYS AND DISPLAY INTO YEARS , MONTHS AND DAYS.*"""

numberOfDays = int(input('Enter the number of days :'))
days = numberOfDays
months = numberOfDays/30.417
years = numberOfDays/365
print("Entered value in days :",days)
print("Entered value in months :",months)
print("Entered value in years : ",years)

"""*8.WRITE A PROGRAM TO DISPLAY SUM , DIFFERENCE , PRODUCT , QUOTIENT AND REMAINDER.*"""

a = int(input('Enter first number : '))
b = int(input('Enter second number :'))
sum = a+b
difference = a-b
product = a*b
quotient = a/b
remainder = a%b
print("SUM IS :",sum)
print("DIFFERENCE IS :",difference)
print("PRODUCT IS :",product)
print("QUOTIENT IS :",quotient)
print("REMAINDER IS :",remainder)