# -*- coding: utf-8 -*-
"""LAB-CYCLE QUESTION NUMBER : 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17cZp-Qn0_1t5JqjohWYR_2uGiX-mHK5c

# *PYTHON LAB-CYCLE QUESTION NUMBER : 01*
"""

#1.Develop a program to read a four digit number and find its:

#a.Sum of digits 

#b.Reverse

#c.Difference between the product of digits at the odd position and the product of digits at the even postion.






n = int(input("Enter a four digit number: "))
digit4 = n%10
n = n//10
digit3 = n%10
n = n//10
digit2 = n%10
n = n//10
digit1 = n%10
n = n//10 
sum = digit4+digit3+digit2+digit1
reverse = (digit4*1000)+(digit3*100)+(digit2*10)+digit1
difference = (digit1*digit3)-(digit2*digit4)
print("sum: ",sum)
print("Reverse is : ",reverse)
print("Difference is : ",difference)