# -*- coding: utf-8 -*-
"""LAB_CYCLE QUESTION:02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gFeiPkDMxA3REOxiSwhtIN9K0kXaKySR

# ***PYTHON LAB_CYCLE QUESTION:02***
"""

#2.Develop a program to read the three sides of two triangles and 
#calculate the area of both. Define a function to read the three sides
#and call it. Also, define a function to calculate the area. Print the total 
#area enclosed by both triangles and each triangle's contribution (%)
#towards it.



def side():
  p = int(input("Enter first side of  triangle: "))
  q = int(input("Enter second side of  triangle : "))
  r = int(input("Enter third side of  triangle : "))
  return p,q,r  
def area():
  p,q,r = side()
  print("Sides of triangle : ",p,q,r)
  s =(p+q+r)*0.5
  A= (s*(s-p)*(s-q)*(s-r))**0.5
  print("AREA OF TRIANGLE : ",A)
  return A
def  contribution():
 a1 =area()
 a2 =area()
 c1 =(a1/(a1+a2)*100)
 c2 =(a2/(a1+a2)*100)
 print("Contribution of first triangle : ",c1)
 print("Contribution of second triangle : ",c2)
contribution()